config/routes.rb
Rails.application.routes.draw do
  resources :afternoon_forms
  resources :morning_forms
  devise_for :users
  resources :users
  resources :teams
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "rails_admin/main#dashboard"
end

app/controllers/afternoon_forms_controller.rb
class AfternoonFormsController < ApplicationController
  before_action :set_afternoon_form, only: [:show, :edit, :update, :destroy]

  # GET /afternoon_forms
  # GET /afternoon_forms.json
  def index
    @afternoon_forms = AfternoonForm.all
  end

  # GET /afternoon_forms/1
  # GET /afternoon_forms/1.json
  def show
  end

  # GET /afternoon_forms/new
  def new
    @afternoon_form = AfternoonForm.new
  end

  # GET /afternoon_forms/1/edit
  def edit
  end

  # POST /afternoon_forms
  # POST /afternoon_forms.json
  def create
    @afternoon_form = AfternoonForm.new(afternoon_form_params)

    respond_to do |format|
      if @afternoon_form.save
        format.html { redirect_to @afternoon_form, notice: 'Afternoon form was successfully created.' }
        format.json { render :show, status: :created, location: @afternoon_form }
      else
        format.html { render :new }
        format.json { render json: @afternoon_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /afternoon_forms/1
  # PATCH/PUT /afternoon_forms/1.json
  def update
    respond_to do |format|
      if @afternoon_form.update(afternoon_form_params)
        format.html { redirect_to @afternoon_form, notice: 'Afternoon form was successfully updated.' }
        format.json { render :show, status: :ok, location: @afternoon_form }
      else
        format.html { render :edit }
        format.json { render json: @afternoon_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /afternoon_forms/1
  # DELETE /afternoon_forms/1.json
  def destroy
    @afternoon_form.destroy
    respond_to do |format|
      format.html { redirect_to afternoon_forms_url, notice: 'Afternoon form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_afternoon_form
      @afternoon_form = AfternoonForm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def afternoon_form_params
      params.require(:afternoon_form).permit(:answer1, :answer2, :user_id)
    end
end

app/helpers/afternoon_forms_helper.rb
module AfternoonFormsHelper
end

app/views/afternoon_forms/_form.html.erb
<%= form_with(model: afternoon_form, local: true) do |form| %>
  <% if afternoon_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(afternoon_form.errors.count, "error") %> prohibited this afternoon_form from being saved:</h2>

      <ul>
      <% afternoon_form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :answer1 %>
    <%= form.text_area :answer1 %>
  </div>

  <div class="field">
    <%= form.label :answer2 %>
    <%= form.text_area :answer2 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/afternoon_forms/edit.html.erb
<h1>Editing Afternoon Form</h1>

<%= render 'form', afternoon_form: @afternoon_form %>

<%= link_to 'Show', @afternoon_form %> |
<%= link_to 'Back', afternoon_forms_path %>

app/views/afternoon_forms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Afternoon Forms</h1>

<table>
  <thead>
    <tr>
      <th>Answer1</th>
      <th>Answer2</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @afternoon_forms.each do |afternoon_form| %>
      <tr>
        <td><%= afternoon_form.answer1 %></td>
        <td><%= afternoon_form.answer2 %></td>
        <td><%= link_to 'Show', afternoon_form %></td>
        <td><%= link_to 'Edit', edit_afternoon_form_path(afternoon_form) %></td>
        <td><%= link_to 'Destroy', afternoon_form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Afternoon Form', new_afternoon_form_path %>

app/views/afternoon_forms/new.html.erb
<h1>New Afternoon Form</h1>

<%= render 'form', afternoon_form: @afternoon_form %>

<%= link_to 'Back', afternoon_forms_path %>

app/views/afternoon_forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Answer1:</strong>
  <%= @afternoon_form.answer1 %>
</p>

<p>
  <strong>Answer2:</strong>
  <%= @afternoon_form.answer2 %>
</p>

<%= link_to 'Edit', edit_afternoon_form_path(@afternoon_form) %> |
<%= link_to 'Back', afternoon_forms_path %>