config/routes.rb
Rails.application.routes.draw do
  resources :afternoon_forms
  resources :morning_forms
  devise_for :users
  resources :users
  resources :teams
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "rails_admin/main#dashboard"
end

app/controllers/morning_forms_controller.rb
class MorningFormsController < ApplicationController
  before_action :set_morning_form, only: [:show, :edit, :update, :destroy]

  # GET /morning_forms
  # GET /morning_forms.json
  def index
    @morning_forms = MorningForm.all
  end

  # GET /morning_forms/1
  # GET /morning_forms/1.json
  def show
  end

  # GET /morning_forms/new
  def new
    @morning_form = MorningForm.new
  end

  # GET /morning_forms/1/edit
  def edit
  end

  # POST /morning_forms
  # POST /morning_forms.json
  def create
    @morning_form = MorningForm.new(morning_form_params)

    respond_to do |format|
      if @morning_form.save
        format.html { redirect_to @morning_form, notice: 'Morning form was successfully created.' }
        format.json { render :show, status: :created, location: @morning_form }
      else
        format.html { render :new }
        format.json { render json: @morning_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /morning_forms/1
  # PATCH/PUT /morning_forms/1.json
  def update
    respond_to do |format|
      if @morning_form.update(morning_form_params)
        format.html { redirect_to @morning_form, notice: 'Morning form was successfully updated.' }
        format.json { render :show, status: :ok, location: @morning_form }
      else
        format.html { render :edit }
        format.json { render json: @morning_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /morning_forms/1
  # DELETE /morning_forms/1.json
  def destroy
    @morning_form.destroy
    respond_to do |format|
      format.html { redirect_to morning_forms_url, notice: 'Morning form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_morning_form
      @morning_form = MorningForm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def morning_form_params
      params.require(:morning_form).permit(:answer1, :answer2, :user_id)
    end
end

app/helpers/morning_forms_helper.rb
module MorningFormsHelper
end

app/views/morning_forms/_form.html.erb
<%= form_with(model: morning_form, local: true) do |form| %>
  <% if morning_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(morning_form.errors.count, "error") %> prohibited this morning_form from being saved:</h2>

      <ul>
      <% morning_form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :answer1 %>
    <%= form.text_area :answer1 %>
  </div>

  <div class="field">
    <%= form.label :answer2 %>
    <%= form.text_area :answer2 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/morning_forms/edit.html.erb
<h1>Editing Morning Form</h1>

<%= render 'form', morning_form: @morning_form %>

<%= link_to 'Show', @morning_form %> |
<%= link_to 'Back', morning_forms_path %>

app/views/morning_forms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Morning Forms</h1>

<table>
  <thead>
    <tr>
      <th>Answer1</th>
      <th>Answer2</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @morning_forms.each do |morning_form| %>
      <tr>
        <td><%= morning_form.answer1 %></td>
        <td><%= morning_form.answer2 %></td>
        <td><%= link_to 'Show', morning_form %></td>
        <td><%= link_to 'Edit', edit_morning_form_path(morning_form) %></td>
        <td><%= link_to 'Destroy', morning_form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Morning Form', new_morning_form_path %>

app/views/morning_forms/new.html.erb
<h1>New Morning Form</h1>

<%= render 'form', morning_form: @morning_form %>

<%= link_to 'Back', morning_forms_path %>

app/views/morning_forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Answer1:</strong>
  <%= @morning_form.answer1 %>
</p>

<p>
  <strong>Answer2:</strong>
  <%= @morning_form.answer2 %>
</p>

<%= link_to 'Edit', edit_morning_form_path(@morning_form) %> |
<%= link_to 'Back', morning_forms_path %>